name: 'Deploy Staging Backend'

on:
  push:
    branches:
      - 'staging'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    environment: 'Preview'

    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v4'

      - name: 'Setup flyctl'
        uses: 'superfly/flyctl-actions/setup-flyctl@master'

      - name: 'Deploy to Fly.io staging'
        run: 'flyctl deploy --config fly.staging.toml --remote-only'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_STAGING }}
