name: 'Deploy Production Backend'

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    environment: 'Production'

    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v4'

      - name: 'Setup flyctl'
        uses: 'superfly/flyctl-actions/setup-flyctl@master'

      - name: 'Deploy to Fly.io production'
        run: 'flyctl deploy --config fly.toml --remote-only'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_PROD }}
